apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sentinelx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sudhirksah333/sentinelx-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: sentinelx-config
                  key: VITE_API_URL
            - name: VITE_WS_URL
              valueFrom:
                configMapKeyRef:
                  name: sentinelx-config
                  key: VITE_WS_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sentinelx
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
