import { useEffect, useState } from 'react';
import { useAuthStore } from '../store/authStore';

export default function AiAnalytics() {
  const API_URL = import.meta.env.VITE_API_URL;
  const { token } = useAuthStore();
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`${API_URL}/api/v1/analytics/ai-insights`, {
      headers: { Authorization: `Bearer ${token}` }
    })
      .then(res => res.json())
      .then(resData => {
        setData(resData);
        setLoading(false);
      })
      .catch(err => console.error(err));
  }, [token]);

  const handleDownloadReport = () => {
    const text = "AI Analytics Report (7 Days)\nAnomaly Detection Average: 82%\nRisk Score: Low\nData Generated by SentinelX";
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = "ai_analytics_report.txt";
    link.click();
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-3xl font-bold text-white tracking-tight">AI & Analytics</h1>
        <div className="flex gap-4">
          <div className="bg-slate-800 rounded-lg p-1 border border-slate-700 flex text-sm">
            <button className="px-3 py-1 bg-slate-700 text-white rounded shadow">7 Days</button>
            <button className="px-3 py-1 text-slate-400 hover:text-white transition-colors">30 Days</button>
          </div>
          <button onClick={handleDownloadReport} className="bg-slate-800 hover:bg-slate-700 text-white px-4 py-2 rounded-lg text-sm font-medium border border-slate-700 transition-all">
            Export JSON
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Mock Chart 1 */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl shadow-xl p-6">
          <h2 className="text-lg font-bold text-white mb-6">Anomaly Detection Confidence</h2>
          <div className="h-64 flex items-end gap-2 pb-6 border-b border-slate-800 relative">
            <div className="absolute inset-y-0 left-0 w-full flex flex-col justify-between z-0">
              {[100, 75, 50, 25, 0].map(val => (
                <div key={val} className="border-b border-slate-800/50 w-full h-0 text-[10px] text-slate-600">
                  <span className="-mt-3 absolute bg-slate-900 pr-2">{val}%</span>
                </div>
              ))}
            </div>
            {/* Dynamic bars */}
            {loading ? (
              <div className="absolute inset-0 flex items-center justify-center text-slate-500 z-20">Loading real data...</div>
            ) : (
              (data?.confidenceScores || [0,0,0,0,0,0,0]).map((h: number, i: number) => (
                <div key={i} className="w-full relative z-10 flex flex-col justify-end group">
                  <div 
                    className={`w-full rounded-t-sm transition-all duration-500 ${h > 75 ? 'bg-red-500/80 hover:bg-red-400 shadow-[0_0_15px_rgba(239,68,68,0.5)]' : h > 50 ? 'bg-orange-500/80 hover:bg-orange-400' : 'bg-blue-600/80 hover:bg-blue-500'}`} 
                    style={{ height: `${h}%` }}
                  ></div>
                  <div className="opacity-0 group-hover:opacity-100 absolute -top-8 left-1/2 -translate-x-1/2 bg-slate-800 text-white text-[10px] px-2 py-1 rounded transition-opacity">
                    Score: {h}
                  </div>
                </div>
              ))
            )}
          </div>
          <div className="flex justify-between mt-2 text-xs text-slate-500">
            <span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span>
          </div>
        </div>

        {/* Behavioral Baselines */}
        <div className="bg-slate-900 border border-slate-800 rounded-2xl shadow-xl p-6">
          <h2 className="text-lg font-bold text-white mb-6">Behavioral Deviations</h2>
          <div className="space-y-6">
            <div>
              <div className="flex justify-between text-sm mb-1.5">
                <span className="text-slate-300">Login Time Deviation</span>
                <span className={data?.deviations?.login > 50 ? "text-red-400 font-mono" : "text-emerald-400 font-mono"}>
                  {loading ? '...' : `+${data?.deviations?.login}%`}
                </span>
              </div>
              <div className="h-2 w-full bg-slate-800 rounded-full overflow-hidden">
                <div className={`h-full rounded-full transition-all duration-1000 ${data?.deviations?.login > 50 ? 'bg-red-500' : 'bg-emerald-500'}`} style={{ width: `${data?.deviations?.login || 0}%` }}></div>
              </div>
            </div>
            
            <div>
              <div className="flex justify-between text-sm mb-1.5">
                <span className="text-slate-300">Data Exfiltration Risk</span>
                <span className={data?.deviations?.dataExfil > 30 ? "text-orange-400 font-mono" : "text-emerald-400 font-mono"}>
                  {loading ? '...' : `+${data?.deviations?.dataExfil}%`}
                </span>
              </div>
              <div className="h-2 w-full bg-slate-800 rounded-full overflow-hidden">
                <div className={`h-full rounded-full transition-all duration-1000 ${data?.deviations?.dataExfil > 30 ? 'bg-orange-500' : 'bg-emerald-500'}`} style={{ width: `${data?.deviations?.dataExfil || 0}%` }}></div>
              </div>
            </div>

            <div>
              <div className="flex justify-between text-sm mb-1.5">
                <span className="text-slate-300">Privilege Escalation Risk</span>
                <span className={data?.deviations?.privEsc > 20 ? "text-red-400 font-mono" : "text-blue-400 font-mono"}>
                  {loading ? '...' : data?.deviations?.privEsc > 20 ? `+${data?.deviations?.privEsc}%` : 'Normal'}
                </span>
              </div>
              <div className="h-2 w-full bg-slate-800 rounded-full overflow-hidden">
                <div className={`h-full rounded-full transition-all duration-1000 ${data?.deviations?.privEsc > 20 ? 'bg-red-500' : 'bg-blue-500'}`} style={{ width: `${data?.deviations?.privEsc || 0}%` }}></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
